export const nameBand = 'EURYTHMICS ';
export let nameSongs = [
	"SWEET DREAMS (ARE MADE OF THIS)", /*1*/
	"THERE MUST BE AN ANGEL", /*2*/
	"HERE COMES THE RAIN AGAIN", /*3*/
	"MISSIONARY MAN", /*4*/
	"WHO'S THAT GIRL?", /*5*/
	"THORN IN MY SIDE", /*6*/
	"WHEN TOMORROW COMES", /*7*/
	"THE MIRACLE OF LOVE", /*8*/
	"LOVE IS A STRANGER", /*9*/
	"WOULD I LIE TO YOU?", /*10*/
	"SISTERS ARE DOIN' IT FOR THEMSELVES", /*11*/
	"IT'S ALRIGHT (BABY'S COMING BACK)", /*12*/
	"SEXCRIME (NINETEEN EIGHTY-FOUR)", /*13*/
	"DOUBLEPLUSGOOD", /*14*/
	"JULIA", /*15*/
	"THIS CITY NEVER SLEEPS", /*16*/
	"17 AGAIN", /*17*/
	"I NEED A MAN", /*18*/
	"BEETHOVEN (I LOVE TO LISTEN TO)", /*19*/
	"SAVAGE", /*20*/
]